# Generated by Django 5.1.4 on 2024-12-12 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
            ],
            options={
                'verbose_name': 'модель',
                'verbose_name_plural': 'модели',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='адрес')),
                ('name', models.CharField(max_length=100, verbose_name='название')),
                ('ip_address', models.CharField(max_length=20, verbose_name='ip-адрес')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.devicemodel', verbose_name='модель')),
            ],
            options={
                'verbose_name': 'устройство',
                'verbose_name_plural': 'устройства',
            },
        ),
    ]
